---
- name: Install Starship
  dnf: name=starship state=latest
  become: yes
- name: Install fish
  dnf:
    name: fish
    state: latest
  become: yes
- name: Install autojump-fish
  dnf:
    name: autojump-fish
    state: latest
  become: yes
- name: Change user shell to fish
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/fish
- name: Install vim
  become: yes
  dnf:
    name: vim-enhanced
    state: latest
- name: Install ripgrep
  become: yes
  dnf:
    name: ripgrep
    state: latest
- name: Install Silver Searcher
  become: yes
  dnf:
    name: the_silver_searcher
    state: latest
- name: Install lsd (ls deluxe)
  become: yes
  dnf:
    name: lsd
    state: latest
- name: Install exa (modern replacement)
  become: yes
  dnf:
    name: exa
    state: latest
