---
- name: Enable atim Copr to install Starship
  become: yes
  community.general.copr:
    state: enabled
    name: atim/starship
- name: Install Starship
  dnf: name=starship state=latest
  become: yes
- name: Install fish
  dnf:
    name: fish
    state: latest
  become: yes
- name: Install autojump-fish
  dnf:
    name: autojump-fish
    state: latest
  become: yes
- name: Change user shell to fish
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/fish
- name: Install vim
  become: yes
  dnf:
    name: vim-enhanced
    state: latest
- name: Install ripgrep
  become: yes
  dnf:
    name: ripgrep
    state: latest
- name: Install Silver Searcher
  become: yes
  dnf:
    name: the_silver_searcher
    state: latest
- name: Install lsd (ls deluxe)
  become: yes
  dnf:
    name: lsd
    state: latest
- name: Install eza (modern ls replacement)
  become: yes
  dnf:
    name: eza
    state: latest
- name: Enable varlad Copr to install Helix
  become: yes
  community.general.copr:
    state: enabled
    name: varlad/helix
- name: Install helix
  become: yes
  dnf:
    name: helix
    state: latest
- name: Install Glow, the CLI Markdown viewer
  become: yes
  dnf:
    name: glow
    state: latest
- name: Install Skate, the personal key-value store
  become: yes
  dnf:
    name: skate
    state: latest
- name: Install Gum, the tool for glamorous CLI scripts
  become: yes
  dnf:
    name: gum
    state: latest
- name: Install bat (modern cat replacement)
  become: yes
  dnf:
    name: bat
    state: latest
- name: Install htop
  become: yes
  dnf:
    name: htop
    state: latest
- name: Install kitty
  become: yes
  dnf:
    name: kitty
    state: latest
- name: Install asciinema
  become: yes
  dnf:
    name: asciinema
    state: latest
- name: Enable copr for ocp-sso-token
  become: yes
  community.general.copr:
    state: enabled
    name: '@cki/ocp-sso-token'
- name: Install ocp-sso-token
  become: yes
  dnf:
    name: ocp-sso-token
    state: latest
