- name: Enable Charm Repository
  become: yes
  yum_repository:
    name: charm
    description: We build tools to make the command line glamorous.
    baseurl: https://repo.charm.sh/yum/
    gpgcheck: yes
    enabled: yes
    gpgkey:
    - https://repo.charm.sh/yum/gpg.key
- name: Enable Google Cloud CLI Repository
  become: yes
  yum_repository:
    name: google-cloud-cli
    description: Google Cloud CLI
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey:
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
