- name: Install DNF upgrade plugin
  dnf:
    name: dnf-plugin-system-upgrade
    state: latest
  become: yes
- name: Install rpmconf
  dnf:
    name: rpmconf
    state: latest
  become: yes
- name: Install GH CLI
  dnf:
    name: gh
    state: latest
  become: yes
- name: Install Discord
  community.general.flatpak:
    name:
    - com.discordapp.Discord
- name: Install Obsidian
  community.general.flatpak:
    name:
    - md.obsidian.Obsidian
- name: Install Slack
  dnf:
    name: slack
    state: latest
  become: yes
